### ISSUE TITLE
ci: cache `sonarcloud` packages

### ISSUE THREAD

**Issue by keinsell** [keinsell/neuronek#256]
```yaml
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          ```
